/** Practical-session groups for Sunday 4 Oct, transcribed from the organisers' handwritten cards. */
export type Group = { id: string; members: string[] };

export const groups: Group[] = [
  {
    id: "1",
    members: [
      "Dr Zaeem Hanef",
      "Dr Alubah",
      "MA Andi",
      "Dr Annuar Deen",
      "Dr Firdaus",
      "En Che Fahmi",
      "Dr Harjeet Singh",
      "Dr Malini",
      "Dr Murti",
      "Ying Chen",
    ],
  },
  {
    id: "2",
    members: [
      "Dr Amir Azwan",
      "Dr Baran",
      "Ms Dona",
      "MA Hasnan",
      "Dr Ihsan",
      "Dr Khoo",
      "Dr Mohd Zaidi",
      "En Mahzuz",
      "Dr Ozair",
      "Dr Aisyah Hamidah",
    ],
  },
  {
    id: "3",
    members: [
      "Dr Amir ‘Ifwat",
      "En Enzo",
      "Dr Ezzat",
      "Ms Faezah",
      "Dr Khairani",
      "Dr Koay",
      "Dr Md Azlan",
      "Dr Faqhroll",
      "Dr Kamal",
      "En Razana",
    ],
  },
  {
    id: "4",
    members: [
      "Dr Ibrahim",
      "Dr Azwan Aziz",
      "Dr Mohamad Zen",
      "Ms Farah Elina",
      "Dr Mohd Khalis",
      "Dr Nuttapat",
      "Dr Thivya Ganeish",
      "Dr Yau Mei Yan",
      "En Zahari Apandi",
      "Dr Rohan",
      "Dr Joshua William",
    ],
  },
  {
    id: "5",
    members: [
      "Dr Keshen",
      "Dr Syamim",
      "Dr Aizat Azam",
      "En Gunalan",
      "Cik Siti Salwa",
      "Dr Puvaneshwaran",
      "Dr Sophee",
      "Dr Ulfah",
      "Dr Mohana Kumar",
      "Dr Muhammad Zaid",
    ],
  },
  {
    id: "6",
    members: [
      "Dr Manivarma",
      "Dr Adam",
      "Dr Fakhrul Sani",
      "Dr Nor Alif",
      "Dr Mugilan",
      "Dr Nuraini",
      "Ms Yap Zhi June",
      "Dr Sudir Kumar",
      "Dr Nurul Sopheiah",
      "Dr Rozaiman",
      "Dr Afiq Razali",
    ],
  },
];
