/** Practical-session groups for Sunday 4 Oct, transcribed from the organisers' handwritten cards. */
export type Group = { id: string; members: string[] };

export const groups: Group[] = [
  {
    id: "1",
    members: [
      "Dr Naeem Hanif",
      "Dr Audah",
      "Andi",
      "Dr A. Anuar Deen",
      "Dr Firdaus",
      "En Che Fahmi",
      "Dr Harjeet Singh",
      "Dr Malini",
      "Dr Murti",
      "Ying Chen",
    ],
  },
  {
    id: "2",
    members: [
      "Dr Amir Adnan",
      "Dr Saran",
      "Ms Dona",
      "Hasnah",
      "Dr Ihsan",
      "Dr Khoo",
      "Dr Mohd Zaki",
      "En Mahfuz",
      "Dr Ozair",
      "Dr Aisyah Hamidah",
    ],
  },
  {
    id: "3",
    members: [
      "Dr Amir ‘Ismat",
      "En Emid",
      "Dr Ezzat",
      "Ms Faezah",
      "Dr Khairani",
      "Dr Koay",
      "Dr Md Azlan",
      "Dr Fakhrull",
      "Dr Kamal",
      "En Razmin",
    ],
  },
  {
    id: "4",
    members: [
      "Dr Ibrahim",
      "Dr Azwan Aziz",
      "Dr Mohamad Zeni",
      "Ms Farah Elina",
      "Dr Mohd Khamis",
      "Dr Nattapat",
      "Dr Thivya Ganesh",
      "Dr Yau Mei Yan",
      "En Zahari Apandi",
      "Dr Rohan",
      "Dr Joshua William",
    ],
  },
  {
    id: "5",
    members: [
      "Dr Keshen",
      "Dr Yamuna",
      "Dr Aizat Azam",
      "En Gunalan",
      "Cik Siti Salwa",
      "Dr Puvaneswaran",
      "Dr Sophee",
      "Dr Ulfah",
      "Dr Mohana Kumar",
      "Dr Muhammad Zaki",
    ],
  },
  {
    id: "6",
    members: [
      "Dr Manivarma",
      "Dr Adam",
      "Dr Fakhrulsani",
      "Dr Nor Alif",
      "Dr Mugilan",
      "Dr Nuraini",
      "Ms Yap Zhi June",
      "Dr Sudir Kumar",
      "Dr Nurul Sopheiah",
      "Dr Rozaiman",
      "Dr Afiq Razali",
    ],
  },
];
