/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CspineRouteImport } from './routes/cspine'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as EventRouteImport } from './routes/event'
import { Route as FifaRouteImport } from './routes/fifa'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as PitchsideRouteImport } from './routes/pitchside'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as RoleIdRouteImport } from './routes/role.$id'
import { Route as SpeakerIdRouteImport } from './routes/speaker.$id'
import { Route as StationIdRouteImport } from './routes/station.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CspineRoute = CspineRouteImport.update({
  id: '/cspine',
  path: '/cspine',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaRoute = FifaRouteImport.update({
  id: '/fifa',
  path: '/fifa',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchsideRoute = PitchsideRouteImport.update({
  id: '/pitchside',
  path: '/pitchside',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleIdRoute = RoleIdRouteImport.update({
  id: '/role/$id',
  path: '/role/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakerIdRoute = SpeakerIdRouteImport.update({
  id: '/speaker/$id',
  path: '/speaker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIdRoute = StationIdRouteImport.update({
  id: '/station/$id',
  path: '/station/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/cspine': typeof CspineRoute
  '/disclaimer': typeof DisclaimerRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/fifa': typeof FifaRoute
  '/focus': typeof FocusRoute
  '/guides': typeof GuidesRoute
  '/pitchside': typeof PitchsideRoute
  '/rules': typeof RulesRoute
  '/stations': typeof StationsRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
  '/station/$id': typeof StationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/cspine': typeof CspineRoute
  '/disclaimer': typeof DisclaimerRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/fifa': typeof FifaRoute
  '/focus': typeof FocusRoute
  '/guides': typeof GuidesRoute
  '/pitchside': typeof PitchsideRoute
  '/rules': typeof RulesRoute
  '/stations': typeof StationsRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
  '/station/$id': typeof StationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/cspine': typeof CspineRoute
  '/disclaimer': typeof DisclaimerRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/fifa': typeof FifaRoute
  '/focus': typeof FocusRoute
  '/guides': typeof GuidesRoute
  '/pitchside': typeof PitchsideRoute
  '/rules': typeof RulesRoute
  '/stations': typeof StationsRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
  '/station/$id': typeof StationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bag'
    | '/cspine'
    | '/disclaimer'
    | '/drill'
    | '/event'
    | '/fifa'
    | '/focus'
    | '/guides'
    | '/pitchside'
    | '/rules'
    | '/stations'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
    | '/station/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bag'
    | '/cspine'
    | '/disclaimer'
    | '/drill'
    | '/event'
    | '/fifa'
    | '/focus'
    | '/guides'
    | '/pitchside'
    | '/rules'
    | '/stations'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
    | '/station/$id'
  id:
    | '__root__'
    | '/'
    | '/bag'
    | '/cspine'
    | '/disclaimer'
    | '/drill'
    | '/event'
    | '/fifa'
    | '/focus'
    | '/guides'
    | '/pitchside'
    | '/rules'
    | '/stations'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
    | '/station/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagRoute: typeof BagRoute
  CspineRoute: typeof CspineRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DrillRoute: typeof DrillRoute
  EventRoute: typeof EventRoute
  FifaRoute: typeof FifaRoute
  FocusRoute: typeof FocusRoute
  GuidesRoute: typeof GuidesRoute
  PitchsideRoute: typeof PitchsideRoute
  RulesRoute: typeof RulesRoute
  StationsRoute: typeof StationsRoute
  TimerRoute: typeof TimerRoute
  RoleIdRoute: typeof RoleIdRoute
  SpeakerIdRoute: typeof SpeakerIdRoute
  StationIdRoute: typeof StationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cspine': {
      id: '/cspine'
      path: '/cspine'
      fullPath: '/cspine'
      preLoaderRoute: typeof CspineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa': {
      id: '/fifa'
      path: '/fifa'
      fullPath: '/fifa'
      preLoaderRoute: typeof FifaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitchside': {
      id: '/pitchside'
      path: '/pitchside'
      fullPath: '/pitchside'
      preLoaderRoute: typeof PitchsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/$id': {
      id: '/role/$id'
      path: '/role/$id'
      fullPath: '/role/$id'
      preLoaderRoute: typeof RoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaker/$id': {
      id: '/speaker/$id'
      path: '/speaker/$id'
      fullPath: '/speaker/$id'
      preLoaderRoute: typeof SpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$id': {
      id: '/station/$id'
      path: '/station/$id'
      fullPath: '/station/$id'
      preLoaderRoute: typeof StationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagRoute: BagRoute,
  CspineRoute: CspineRoute,
  DisclaimerRoute: DisclaimerRoute,
  DrillRoute: DrillRoute,
  EventRoute: EventRoute,
  FifaRoute: FifaRoute,
  FocusRoute: FocusRoute,
  GuidesRoute: GuidesRoute,
  PitchsideRoute: PitchsideRoute,
  RulesRoute: RulesRoute,
  StationsRoute: StationsRoute,
  TimerRoute: TimerRoute,
  RoleIdRoute: RoleIdRoute,
  SpeakerIdRoute: SpeakerIdRoute,
  StationIdRoute: StationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
