/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BagRouteImport } from './routes/bag'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as EventRouteImport } from './routes/event'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as RoleIdRouteImport } from './routes/role.$id'
import { Route as SpeakerIdRouteImport } from './routes/speaker.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleIdRoute = RoleIdRouteImport.update({
  id: '/role/$id',
  path: '/role/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakerIdRoute = SpeakerIdRouteImport.update({
  id: '/speaker/$id',
  path: '/speaker/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/guides': typeof GuidesRoute
  '/rules': typeof RulesRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/guides': typeof GuidesRoute
  '/rules': typeof RulesRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/drill': typeof DrillRoute
  '/event': typeof EventRoute
  '/guides': typeof GuidesRoute
  '/rules': typeof RulesRoute
  '/timer': typeof TimerRoute
  '/role/$id': typeof RoleIdRoute
  '/speaker/$id': typeof SpeakerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bag'
    | '/drill'
    | '/event'
    | '/guides'
    | '/rules'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bag'
    | '/drill'
    | '/event'
    | '/guides'
    | '/rules'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
  id:
    | '__root__'
    | '/'
    | '/bag'
    | '/drill'
    | '/event'
    | '/guides'
    | '/rules'
    | '/timer'
    | '/role/$id'
    | '/speaker/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagRoute: typeof BagRoute
  DrillRoute: typeof DrillRoute
  EventRoute: typeof EventRoute
  GuidesRoute: typeof GuidesRoute
  RulesRoute: typeof RulesRoute
  TimerRoute: typeof TimerRoute
  RoleIdRoute: typeof RoleIdRoute
  SpeakerIdRoute: typeof SpeakerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/$id': {
      id: '/role/$id'
      path: '/role/$id'
      fullPath: '/role/$id'
      preLoaderRoute: typeof RoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaker/$id': {
      id: '/speaker/$id'
      path: '/speaker/$id'
      fullPath: '/speaker/$id'
      preLoaderRoute: typeof SpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagRoute: BagRoute,
  DrillRoute: DrillRoute,
  EventRoute: EventRoute,
  GuidesRoute: GuidesRoute,
  RulesRoute: RulesRoute,
  TimerRoute: TimerRoute,
  RoleIdRoute: RoleIdRoute,
  SpeakerIdRoute: SpeakerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
